[project]
name = "MIMo"
version = "1.0.0"

authors = [
    {name = "Marco Gabriele Fedozzi", email = "marco.fedozzi@iit.it" },
    {name = "Francisco M. López", email = "lopez@fias.uni-frankfurt.de"},
    {name = "Dominik Mattern"},
    {name = "Miles Lenz"},
    {name = "Pierre Schumacher"}
]

description = "MIMo library"

readme = "README.md"
requires-python = ">=3.9"

license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "cachetoolsutils>=6.0",
    "gymnasium==0.28.1",
    "imageio>=2.37.2",
    "matplotlib>=3.9.4",
    "mujoco==2.3.7",
    "networkx>=3.2.1",
    "opencv-python-headless>=4.12.0.88",
    "rtree>=1.4.1",
    "scikit-image>=0.24.0",
    "swig>=4.4.0",
    "trimesh>=4.10.1",
]

[project.urls]

Documentation = "https://mimo.readthedocs.io/en/latest/"
Repository = "https://github.com/trieschlab/MIMo/"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
# Include any .xml and .json files that are inside the MIMo package (recursively).
# Adjust the package name ("MIMo") if your actual Python package dir has a different name.
# The XML/JSON files live under the Python package `mimoEnv` (and its subpackages).
# Use recursive globs so files in subfolders are included in the wheel/sdist.
"mimoEnv" = ["**/*.xml", "**/*.json", "**/*.png"]
